name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # ou la branche que vous souhaitez utiliser

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '10.9.0'  # ou la version que vous utilisez
      - name: Install Firebase Tools
        run: npm install -g firebase-tools
      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy --non-interactive
